require("../app/components/text-example/text.story")
// require("../app/components/auto-image-example/auto-image.story")
require("../app/components/button-example/button.story")
require("../app/components/form-row-example/form-row.story")
require("../app/components/switch-example/switch.story")
require("../app/components/text-field-example/text-field.story")
require("../app/components/checkbox-example/checkbox.story")
require("../app/components/wallpaper-example/wallpaper.story")
require("../app/components/icon-example/icon.story")
require("../app/components/header-example/header.story")
